// Generated by tools/encrypt — do not edit by hand.
window.TRIP_SECRET = {
  "version": 1,
  "kdf": {
    "name": "PBKDF2",
    "hash": "SHA-256",
    "iterations": 200000
  },
  "cipher": "AES-GCM",
  "salt": "/gZlCCuQ5ssb9zEL3LT3NA==",
  "sentinel": {
    "iv": "PV+oa8coLqYWBC/B",
    "ct": "f9xjDBW3j5Idz5Cw3tOOEekDualGALuDdtY1Kg=="
  },
  "payloads": {
    "flight": {
      "iv": "6P9tvViq3dDMWQII",
      "ct": "eYPu7RE/1xD+CyBcuV5dCz9vxvSR9u1g7VAT215QeSk/x5hAmvl4K2eqbwenxjYfG0KstWxct6qY69RGDzMauyNoGdgGJjWtRI1mnJTEm3xPnaK5A0sTAlhkqRAtTrm3lil+CkkEjjGGFSqEBWl9YCYkQE05p8VGvFSEEgvn5WsCe5O637MVYPSBRVQYiFDbC4YYI0TS8x0tP/rTMPc/agdoIAipNnGoTStgucsGh++al4yHhEYfzY7d/W4XN0ficjxT8GmQ/Vxgt0oaVIAGJBrLrC5G10vOIxF+CTxq/XequOMkJHmboI70K6TA8NN7n6Trs7DJBFqLNYN/vIC4B7+7wgGq2QpXR+cpZi9T7gh1yikvsuexvvU7Xj8q4Q8HvhphHWv6tfp2MIucoX52Z/Svn+i+IMLGhZfeDEQcj0cHZoFb74BDuYUpb5V6udINacqmpJTIqCY5QHhBTXkt8Rr3qMddJISiqAbhuEYYlpaHBGJD0RiZhPYoYFuxYuZ7W5pq/eRMTFrm6RYJeJvea9q31WYzXuM1IsmpZkooZR/FW9/S2eJPAoud1WEdlz2nC6JOepW44n1CQmwR/CgT99/S5oPUd5n13Lo9ebnLXG2uCeTI/FLM9YcWko+CK180BKXfRiq25BVzbEpJWSQrzK5ml0sOGZv3cwwRVOd3D+rgtHIDD2pGmdFad4JJWfQP3zexuXtIwwBbObqt63hfBkkeRECboaskqtQFHTOJ/kC5fFiNi0bYOUbxfyCvzcJtSqpCyue5ynehUw=="
    }
  }
};
