// Generated by tools/encrypt — do not edit by hand.
window.TRIP_SECRET = {
  "version": 1,
  "kdf": {
    "name": "PBKDF2",
    "hash": "SHA-256",
    "iterations": 200000
  },
  "cipher": "AES-GCM",
  "salt": "3XQR3+CtPvy1rY9fu+uYQw==",
  "sentinel": {
    "iv": "t1nzr7hkT3iB8hDx",
    "ct": "faEN4y0Qu9FpTADDfRq0aoUUhmCUFOmlKqwH7w=="
  },
  "payloads": {
    "flight": {
      "iv": "5dJFYe9cg9vQFANK",
      "ct": "/cRV1iU/RdxmwLdtJF9Gu6DzYOgTLPj9QIuHfCBqVrW5vExnaXXgFQlwt6JoCgxArT8+pSF7PSTGiFk5ypBmZJuPl9IdYzki0rJsD+YJCxt9xg2Fvjl56jAeOFb8tF0zh4V7/epfZgNvJIXFrn2bEr8fWZ58D0o1eEuKI34Mj6KGCD3kaj6u8kGOmwRRDmmZ5A6g5tD0vs0nVQxcVFvYH0v85Yg+Qf7ffjZWs3XmLfvuAgClxSapmpR1uKwm98pmHt8L20EdgXkfo1oCD9/mZT27df5LigcoZC5Fz7BD+0jE5kPDax73F9gGmcD6RTGG0th+iNIoRTkHgKvrTDoNLFQE4heCH6sEqcw95ZSvrYEna7MLsD2Nm5+XGY6rrR8HZpgGsCUjM9t9GwE/HyJvJX6fLh4zDbJprMMIxmAUG5KU7O1unzf1BAY9Id33ayQhol2hTXFqDAaqGTWNbAE92EzBr3G4UWBs/6H9EyBnq/RgYkuP68Ff71FNsEhqlj4gRYVTIazKf8psWIzSDTl9GdHTPMcQvlJAmKALa5irLQkABZx3TeO55CZHAnE0rXYRUWm1L+A7LREwbT6wDL4RP/7xCLPUv1Ko+DJG8i3/q/UlvAxpMYi5ODPnAe0lN6jygHxw3wC7tRil5ENIg9XZ8Mx90d8VYJRmKELuUER5TJOSOZpr9MqvCHKiAewOxE+mYmyklDVZ6JONOyrZjPgq4OFK2dzqwn4e1kTefyA3qAdRjvw/FK7AIQ9tUzO2fNQPmBlgL16biZYSFgYBSQRgkar+nUsU+zN2xewpktgqHPjYDTSfeMj3l+uhYAaySvIUspfjY4ch6oQUk/saBRRu3NgmoXNPzN4Ur4vz+XOU3IC71x2N4kAGPAI++bm9CMn4Qgs2fQ6e2LmkZE1PEpRN5TxEtwNES/6wZHDFND02b0en48fp1na9+Q+jUkWjb5+HigYsZC+xM2f92nV0+YpOkvaWFQR+jXGj/L3iRMhQx5zu720GdgElre7oEY80uGIXKt1lm4tKsWDrEtTpsW+bng=="
    }
  }
};
